<?PHP
 
	class Consts {		
		const RESULT = "result";
		const SUCCESS = "SUCCESS";
		const EMAIL_NOT_FAIL = "EMAIL_NOT_FAIL";
		const EMAIL_DIFFERENT_FAIL = "EMAIL_DIFFERENT_FAIL";
		const PASSWORD_FAIL = "PASSWORD_FAIL";
		const REGISTER_DUPLICATION = "REGISTER_DUPLICATION";
		const REGISTER_NONEXISTENT = "EMAIL_NONEXISTENT";
		const REGISTER_KAKAO_NONEXISTENT = "REGISTER_KAKAO_NONEXISTENT";		
		const LOGIN_PASSWORD_FAIL = "LOGIN_PASSWORD_FAIL";
		const LOGIN_SESSION_FAIL = "LOGIN_SESSION_FAIL";
		const MAIN_PORTFOLIO_DATA_NULL = "MAIN_PORTFOLIO_DATA_NULL";
		const PORTFOLIO_COMMENT_DATA_NULL = "PORTFOLIO_COMMENT_DATA_NULL";
		const LIKE_EXISTENT = "LIKE_EXISTENT";
		const UNLIKE_FAIL = "UNLIKE_FAIL";
		const REQUEST_PARAMS_FAIL = "REQUEST_PARAMS_FAIL";
		const FOLLOW_DUPLICATION  = "FOLLOW_DUPLICATION";
		const DATA_NULL = "DATA_NULL";		
		const DATA_UPLOAD_FAIL = "DATA_UPLOAD_FAIL";
		const REQUEST_REMOVE_FAIL = "REQUEST_REMOVE_FAIL";	
		const REQUEST_MESSAGE_READ_FAIL = "REQUEST_MESSAGE_READ_FAIL";	
		const REQUEST_MESSAGE_WRITE_FAIL = "REQUEST_MESSAGE_WRITE_FAIL";
		const REQUEST_MESSAGE_REMOVE_FAIL = "REQUEST_MESSAGE_REMOVE_FAIL";	
		const REQUEST_LIKE_READ_FAIL = "REQUEST_LIKE_READ_FAIL";	
		const REQUEST_RROFILE_UPDATE_FAIL = "REQUEST_RROFILE_UPDATE_FAIL";
		const REQUEST_EXTENSION_FAIL = "REQUEST_EXTENSION_FAIL";
		const REQUEST_PASSWORD_FAIL = "REQUEST_PASSWORD_FAIL";
		const EMAIL_DUPLICATION_FAIL = "EMAIL_DUPLICATION_FAIL";
		
		
		const REQUEST_FACEBOOK_LOGIN = 1;
		const REQUEST_LOGIN = 2;	
		const REQUEST_KAKAO_LOGIN = 3;			
		
		const REQUEST_PORTFOLIO_NEW = 1;
		const REQUEST_PORTFOLIO_BEST = 2;
		const REQUEST_PORTFOLIO_FOLLOW = 3;		
		
		const REQUEST_FOLLOWER = 1;
		const REQUEST_FOLLOWING = 2;
		
		
		const REQUEST_INBOX = 1;
		const REQUEST_OUTBOX = 2;
		
		
		const REQUEST_USER_LIKE_HISTORY = 1;
		const REQUEST_LIKE_HISTORY = 2;
	}

?>